#!/bin/bash
# ---------------------------------------------------------------------------
# M11 guard library — production meshes are READ-ONLY.
#
#   source scripts/m11_guards.sh        (library use, from jobs and scripts)
#   bash   scripts/m11_guards.sh selftest   (verification, Task 1)
#
# Why this exists: the FESOM partitioner writes into MeshPath. It regenerates
# edges.out/edge_tri.out/edgenum.out when absent and rewrites nlvls.out /
# elvls.out from freshly recomputed in-memory levels (FESOM/fesom2#852,
# fvom_init.F90:663-683,996-1017), and every partition run drops a dist_N/
# directory next to the mesh files. That has ALREADY happened to production
# meshes on this account: /pool/.../MESHES_FESOM2.1/{core2,farc,dars,ng5} all
# carry edges/edge_tri/edgenum/nlvls/elvls owned by a270088 and dated
# 2026-05-28…2026-07-03. M11 generates hundreds of partitions, so the hazard is
# structural, not incidental.
#
# The three real write paths and the guard that closes each:
#   1. symlink write-through .......... m11_sandbox_copy_mesh uses `cp -aL`,
#                                       then m11_assert_no_symlinks
#   2. MeshPath escape (sed typo) ..... m11_assert_namelist_meshpath re-reads
#                                       the value FROM the namelist after sed
#                                       and resolves it with `readlink -m`
#   3. source-side writes ............. m11_sources_init + m11_check_sources
#                                       (md5 of the gate files + an mtime sweep
#                                       against a job-start marker)
#
# Every guard fails CLOSED: it prints "M11-GUARD ABORT" and exits 1. Callers
# that want to survive a failure must run the guard in a subshell.
# ---------------------------------------------------------------------------

# --- configuration ---------------------------------------------------------

M11_SANDBOX_ROOT=${M11_SANDBOX_ROOT:-/work/ab0995/a270088/port2/mesh_m11}
M11_STATE_DIR=${M11_STATE_DIR:-$M11_SANDBOX_ROOT/.m11state}

# The five files the md5 gate covers: what the partitioner mutates plus what
# the model and the scorecard read as ground truth.
M11_GATE_FILES=(nod2d.out elem2d.out aux3d.out nlvls.out elvls.out)
# Regenerated by the partitioner; deleted on purpose when renumbering (Task 5).
M11_EDGE_FILES=(edges.out edge_tri.out edgenum.out)

# Registered read-only sources. Override M11_SOURCES to extend (Task 15 adds
# dars/ng5). Format: name=path
M11_SOURCES=${M11_SOURCES:-"core2=/work/ab0995/a270088/port2/mesh/core2 farc=/pool/data/AWICM/FESOM2/MESHES_FESOM2.1/farc"}

# Any resolved path under one of these is NEVER writable by M11 (belt and
# braces behind the positive sandbox test). Trailing slash matters:
# .../port2/mesh/ must not match the sandbox .../port2/mesh_m11.
# NOTE: /pool/data/... is itself a symlink into /work/pd1284/..., so a resolved
# path never starts with /pool — the real project root has to be listed too.
M11_FORBIDDEN_ROOTS=(/pool/ /work/pd1284/ /work/ab0995/a270088/port2/mesh/ /home/)

# --- primitives ------------------------------------------------------------

m11_die() {
    printf 'M11-GUARD ABORT: %s\n' "$*" >&2
    exit 1
}

m11_ok() { printf 'M11-GUARD ok: %s\n' "$*"; }

# Canonicalize, resolving symlinks in every existing component. `readlink -m`
# (not -f) so a path that does not exist yet still resolves — the sandbox
# assert has to run BEFORE mkdir, not after.
m11_resolve() {
    [ -n "${1:-}" ] || m11_die "m11_resolve called with an empty path"
    readlink -m -- "$1"
}

# --- guard 1: is this path inside the sandbox? -----------------------------

# m11_assert_sandbox <path> [<what>]
# Aborts unless <path> resolves to a location strictly inside the sandbox root.
m11_assert_sandbox() {
    local raw=${1:-}
    local what=${2:-path}
    [ -n "$raw" ] || m11_die "$what: empty path passed to m11_assert_sandbox"

    local root; root=$(m11_resolve "$M11_SANDBOX_ROOT")
    local p;    p=$(m11_resolve "$raw")

    # The sandbox root must not itself have been redirected somewhere silly.
    case "$root" in
        /work/ab0995/a270088/port2/mesh_m11*) : ;;
        *) m11_die "sandbox root $M11_SANDBOX_ROOT resolves to $root — refusing to trust it" ;;
    esac

    local r
    for r in "${M11_FORBIDDEN_ROOTS[@]}"; do
        case "$p/" in
            "$r"*) m11_die "$what: $raw resolves to $p — inside protected tree $r" ;;
        esac
    done

    # strictly INSIDE: the root itself is not a legal target (a mesh dir, a
    # manifest or a dist must live in a named subdirectory)
    [ "$p" != "$root" ] || m11_die "$what: $raw is the sandbox root itself, not a directory inside it"
    case "$p/" in
        "$root"/?*) : ;;
        *) m11_die "$what: $raw resolves to $p — outside the M11 sandbox $root" ;;
    esac
    printf '%s\n' "$p"
}

# m11_assert_no_symlinks <dir>
m11_assert_no_symlinks() {
    local d=${1:?m11_assert_no_symlinks needs a directory}
    [ -d "$d" ] || m11_die "m11_assert_no_symlinks: $d is not a directory"
    local hits; hits=$(find "$d" -type l -print 2>/dev/null | head -5)
    [ -z "$hits" ] || m11_die "symlinks inside $d (write-through hazard):
$hits"
}

# --- guard 2: MeshPath as the namelist actually spells it ------------------

# m11_namelist_meshpath <namelist.config> -> prints the MeshPath value
m11_namelist_meshpath() {
    local nml=${1:?m11_namelist_meshpath needs a namelist}
    [ -f "$nml" ] || m11_die "namelist $nml not found"
    local v
    v=$(sed -n "s/^[[:space:]]*MeshPath[[:space:]]*=[[:space:]]*'\([^']*\)'.*/\1/p" "$nml" | tail -1)
    [ -n "$v" ] || m11_die "no MeshPath assignment found in $nml"
    printf '%s\n' "$v"
}

# m11_assert_namelist_meshpath <namelist.config> [<expected_dir>]
# Re-reads MeshPath FROM THE FILE (never from the variable the sed was built
# from) and asserts it is in the sandbox; optionally that it is the directory
# the caller believes it wrote.
m11_assert_namelist_meshpath() {
    local nml=${1:?needs a namelist}
    local expect=${2:-}
    local v; v=$(m11_namelist_meshpath "$nml") || exit 1
    local p; p=$(m11_assert_sandbox "$v" "MeshPath in $nml") || exit 1
    if [ -n "$expect" ]; then
        local e; e=$(m11_resolve "$expect")
        [ "$p" = "$e" ] || m11_die "MeshPath in $nml resolves to $p, expected $e"
    fi
    printf '%s\n' "$p"
}

# --- guard 3: the sources have not moved ----------------------------------

m11_source_list() { printf '%s\n' $M11_SOURCES; }

# md5 of the gate + edge files of one mesh dir, as "name/file  md5" lines.
_m11_mesh_digest() {
    local name=$1 dir=$2 f h
    for f in "${M11_GATE_FILES[@]}" "${M11_EDGE_FILES[@]}"; do
        if [ -f "$dir/$f" ]; then
            h=$(md5sum "$dir/$f" | cut -d' ' -f1)
        else
            h="ABSENT"
        fi
        printf '%s/%s  %s\n' "$name" "$f" "$h"
    done
}

# m11_sources_init — call once at the start of every job that runs the
# partitioner. Creates the md5 baseline on first use (and never silently
# rewrites it), and drops the mtime marker the sweep compares against.
m11_sources_init() {
    mkdir -p "$M11_STATE_DIR" || m11_die "cannot create $M11_STATE_DIR"
    local base=$M11_STATE_DIR/source_md5.txt
    local tmp=$M11_STATE_DIR/.source_md5.$$
    local entry name dir
    : > "$tmp"
    for entry in $(m11_source_list); do
        name=${entry%%=*}; dir=${entry#*=}
        [ -d "$dir" ] || m11_die "registered source $name -> $dir does not exist"
        _m11_mesh_digest "$name" "$dir" >> "$tmp"
    done
    if [ -f "$base" ]; then
        if ! diff -q "$base" "$tmp" >/dev/null; then
            printf 'M11-GUARD ABORT: source mesh files changed since the M11 baseline\n' >&2
            diff "$base" "$tmp" >&2
            rm -f "$tmp"; exit 1
        fi
        rm -f "$tmp"
    else
        mv "$tmp" "$base"
        m11_ok "source md5 baseline written: $base ($(wc -l < "$base") entries)"
    fi
    : > "$M11_STATE_DIR/job_start_marker"
    m11_ok "source guard armed (marker $M11_STATE_DIR/job_start_marker, $(date '+%F %T'))"
}

# m11_check_sources — run after EVERY partitioner invocation.
#   (a) gate-file md5s still match the baseline
#   (b) nothing under any registered source is newer than the job-start marker
m11_check_sources() {
    local base=$M11_STATE_DIR/source_md5.txt
    local marker=$M11_STATE_DIR/job_start_marker
    [ -f "$base" ]   || m11_die "m11_check_sources before m11_sources_init (no $base)"
    [ -f "$marker" ] || m11_die "m11_check_sources before m11_sources_init (no $marker)"

    local tmp=$M11_STATE_DIR/.source_md5_check.$$
    local entry name dir
    : > "$tmp"
    for entry in $(m11_source_list); do
        name=${entry%%=*}; dir=${entry#*=}
        _m11_mesh_digest "$name" "$dir" >> "$tmp"
    done
    if ! diff -q "$base" "$tmp" >/dev/null; then
        printf 'M11-GUARD ABORT: a source mesh file was MODIFIED\n' >&2
        diff "$base" "$tmp" >&2
        rm -f "$tmp"; exit 1
    fi
    rm -f "$tmp"

    local hits=""
    for entry in $(m11_source_list); do
        name=${entry%%=*}; dir=${entry#*=}
        local h; h=$(find "$dir" -newer "$marker" -print 2>/dev/null | head -5)
        [ -z "$h" ] || hits="$hits
[$name] $h"
    done
    [ -z "$hits" ] || m11_die "new/modified entries under a read-only source mesh:$hits"
    m11_ok "sources clean (md5 + mtime sweep)"
}

# --- md5 manifests for sandbox meshes -------------------------------------

# _m11_md5_write_dir <already-asserted dir> — no path assertion of its own, so every caller must
# have run the assert appropriate to ITS root (sandbox or promote) first.
_m11_md5_write_dir() {
    local d=${1:?needs a dir}
    [ -d "$d" ] || m11_die "m11_md5_write: $d is not a directory"
    local f out=$d/MD5MANIFEST
    {
        printf '# M11 mesh manifest — written %s\n' "$(date '+%F %T')"
        printf '# gate files: %s\n' "${M11_GATE_FILES[*]}"
        printf '# edge files (regenerable): %s\n' "${M11_EDGE_FILES[*]}"
        for f in "${M11_GATE_FILES[@]}" "${M11_EDGE_FILES[@]}"; do
            [ -f "$d/$f" ] && md5sum "$d/$f" | sed "s#$d/##"
        done
    } > "$out"
    m11_ok "manifest $out ($(grep -c '^[0-9a-f]' "$out") files)"
}

# m11_md5_write <sandbox_meshdir>
m11_md5_write() {
    local d; d=$(m11_assert_sandbox "${1:?m11_md5_write needs a mesh dir}" "md5_write target") || exit 1
    _m11_md5_write_dir "$d"
}

# m11_md5_check <meshdir> [--gate-only]
# Read-only: usable on any mesh dir that carries a manifest.
m11_md5_check() {
    local d=${1:?m11_md5_check needs a mesh dir}
    local mode=${2:-all}
    local man=$d/MD5MANIFEST
    [ -f "$man" ] || m11_die "no MD5MANIFEST in $d"
    local bad=0 line h f cur
    while read -r h f; do
        case "$h" in '#'*|'') continue ;; esac
        if [ "$mode" = "--gate-only" ]; then
            case " ${M11_GATE_FILES[*]} " in *" $f "*) : ;; *) continue ;; esac
        fi
        if [ ! -f "$d/$f" ]; then
            printf 'M11-GUARD: %s/%s MISSING (manifest %s)\n' "$d" "$f" "$h" >&2; bad=1; continue
        fi
        cur=$(md5sum "$d/$f" | cut -d' ' -f1)
        [ "$cur" = "$h" ] || { printf 'M11-GUARD: %s/%s md5 %s != manifest %s\n' "$d" "$f" "$cur" "$h" >&2; bad=1; }
    done < "$man"
    [ "$bad" = 0 ] || m11_die "md5 manifest mismatch in $d"
    m11_ok "md5 manifest verified: $d"
}

# --- sandbox construction --------------------------------------------------

# m11_sandbox_copy_mesh <src_mesh_dir> <dst_name> [dist_N ...]
# Copies the model-required mesh files (and any named dist dirs) into
# $M11_SANDBOX_ROOT/<dst_name> with `cp -aL` (dereference: a symlinked source
# file becomes a real file here, so a later write can never travel back), then
# asserts the copy is symlink-free and writes the manifest.
m11_sandbox_copy_mesh() {
    local src=${1:?src mesh dir}; shift
    local name=${1:?dst name}; shift
    local dst; dst=$(m11_assert_sandbox "$M11_SANDBOX_ROOT/$name" "sandbox copy target") || exit 1
    [ -d "$src" ] || m11_die "source mesh $src not found"
    mkdir -p "$dst" || m11_die "cannot create $dst"

    local f
    for f in "${M11_GATE_FILES[@]}" "${M11_EDGE_FILES[@]}"; do
        [ -f "$src/$f" ] || m11_die "source $src is missing $f"
        cp -aL "$src/$f" "$dst/$f" || m11_die "cp -aL failed for $f"
    done
    local d
    for d in "$@"; do
        [ -d "$src/$d" ] || m11_die "source $src has no $d"
        cp -aL "$src/$d" "$dst/" || m11_die "cp -aL failed for $d"
    done
    chmod -R u+w "$dst" 2>/dev/null
    m11_assert_no_symlinks "$dst"
    {
        printf '# M11 sandbox mesh copy\n'
        printf 'source: %s\n' "$(m11_resolve "$src")"
        printf 'copied: %s\n' "$(date '+%F %T')"
        printf 'files : %s %s\n' "${M11_GATE_FILES[*]}" "${M11_EDGE_FILES[*]}"
        printf 'dists : %s\n' "${*:-none}"
        printf 'tool  : scripts/m11_guards.sh m11_sandbox_copy_mesh (cp -aL)\n'
    } > "$dst/MESH_PROVENANCE.md"
    m11_md5_write "$dst"
    m11_ok "sandbox mesh $dst ready"
}

# --- adoption packaging (Task 16) ------------------------------------------
#
# m11_promote is the ONE sanctioned way a partition leaves the campaign. It creates a NEW
# directory and refuses to touch an existing one, so a promotion can never silently redefine a
# mesh other runs are already pointing at.
#
# It also refuses to promote a dist_N that has no PASSING RUN RECORD at exactly N ranks, of at
# least M11_MIN_PROMOTE_STEPS steps. That rule is the NG5 finding made mechanical, and the step
# floor is the part that finding actually taught us.
#
# `a4m` (MINCONN) on NG5 is the campaign's best partition at 64 GPU ranks (-9.96 %) and dies at
# 2048 CPU ranks with a NaN in the SSH solve. Nothing we can compute offline separates it from
# the arm that survives: it is the CLEANER partition on every fragmentation metric, its
# owned-node imbalance matches, no rank owns zero nodes, and the halo identity gate passes.
# But it is not un-startable either — a FIVE-STEP smoke of that exact partition passes, and so
# would a 20-step gate. It dies later in the run. So "smoke it first" is necessary and not
# sufficient: the bar has to be the protocol-length stability screen (rule 0.41), which is the
# only test that has actually separated a shippable partition from an unshippable one.
#
#   m11_promote --src <sandbox_meshdir> --name core2_v2 --evidence <file> dist_512 dist_4
#
# Evidence file: one line per dist, whitespace-separated key=value pairs. `run=<jobid>`,
# `steps=<N>` and `rc=0` are mandatory; everything else is carried into MESH_PROVENANCE.md as
# the audit trail.
#
#   dist_512  run=26886214 steps=3000 rc=0  race=26884270 delta=-3.83%  gate=26885353 in-class
#
M11_MIN_PROMOTE_STEPS=${M11_MIN_PROMOTE_STEPS:-3000}
M11_PROMOTE_ROOT=${M11_PROMOTE_ROOT:-/work/ab0995/a270088/port2/mesh_m11_certified}

# m11_assert_promote_root <path> [<what>] — same shape as m11_assert_sandbox, different root.
m11_assert_promote_root() {
    local raw=${1:-} what=${2:-path}
    [ -n "$raw" ] || m11_die "$what: empty path passed to m11_assert_promote_root"
    local root; root=$(m11_resolve "$M11_PROMOTE_ROOT")
    case "$root" in
        /work/ab0995/a270088/port2/mesh_m11_certified*) : ;;
        *) m11_die "promote root $M11_PROMOTE_ROOT resolves to $root — refusing to trust it" ;;
    esac
    local p r; p=$(m11_resolve "$raw")
    for r in "${M11_FORBIDDEN_ROOTS[@]}"; do
        case "$p/" in "$r"*) m11_die "$what: $raw resolves to $p — inside protected tree $r" ;; esac
    done
    [ "$p" != "$root" ] || m11_die "$what: $raw is the promote root itself"
    case "$p/" in "$root"/?*) : ;; *) m11_die "$what: $raw resolves to $p — outside $root" ;; esac
    printf '%s\n' "$p"
}

# _m11_evidence_for <evidence_file> <dist_N> — prints the line, or nothing.
_m11_evidence_for() {
    sed -n "s/^[[:space:]]*$2[[:space:]]\+\(.*\)$/\1/p" "$1" | head -1
}

m11_promote() {
    # --src may be repeated: it applies to every dist_N named after it, until the next --src.
    # The campaign's central result is that the best setting is rank-dependent, so the CPU winner
    # at 512 ranks and the GPU winner at 4 ranks routinely come from DIFFERENT arms of the same
    # mesh. A certified mesh has to be able to carry both.
    local name="" evidence="" src="" dists=() srcs=()
    while [ $# -gt 0 ]; do
        case "$1" in
            --src)      src=${2:?--src needs a value}; shift 2 ;;
            --name)     name=${2:?--name needs a value}; shift 2 ;;
            --evidence) evidence=${2:?--evidence needs a value}; shift 2 ;;
            dist_*)     [ -n "$src" ] || m11_die "m11_promote: $1 named before any --src"
                        dists+=("$1"); srcs+=("$src"); shift ;;
            *) m11_die "m11_promote: unexpected argument '$1'" ;;
        esac
    done
    [ -n "$name" ] || m11_die "m11_promote needs --name <new certified dir name>"
    [ -n "$evidence" ] || m11_die "m11_promote needs --evidence <file>"
    [ -f "$evidence" ] || m11_die "m11_promote: evidence file $evidence not found"
    [ ${#dists[@]} -gt 0 ] || m11_die "m11_promote: name at least one dist_N to promote"

    # Every source must be a sandbox mesh with a verified manifest — promotion publishes campaign
    # output, never production data and never anything from outside the guarded tree.
    local i s resolved=() first=""
    for i in "${!dists[@]}"; do
        s=$(m11_assert_sandbox "${srcs[$i]}" "promote source") || exit 1
        [ -d "$s" ] || m11_die "promote source $s is not a directory"
        m11_md5_check "$s" >/dev/null || exit 1
        resolved[$i]=$s
        [ -n "$first" ] || first=$s
    done

    # ...and every source must be the SAME mesh, or the promoted directory would carry mesh files
    # from one arm and partitions built for another's numbering.
    local f h0 hi
    for f in "${M11_GATE_FILES[@]}"; do
        h0=$(md5sum "$first/$f" | cut -d' ' -f1)
        for i in "${!resolved[@]}"; do
            hi=$(md5sum "${resolved[$i]}/$f" 2>/dev/null | cut -d' ' -f1)
            [ "$hi" = "$h0" ] || m11_die "promote sources disagree on $f: \
${resolved[$i]} vs $first — these are different meshes, not different partitions of one mesh"
        done
    done
    s=$first

    local dst; dst=$(m11_assert_promote_root "$M11_PROMOTE_ROOT/$name" "promote target") || exit 1
    [ -e "$dst" ] && m11_die "promote target $dst already exists — promotion never overwrites; \
pick a new name (core2_v3, ...) so nothing already pointing at $name changes underneath it"

    # Every dist must carry a passing smoke record AT ITS OWN RANK COUNT before it is copied.
    local d line n bad=0 idx
    for idx in "${!dists[@]}"; do
        d=${dists[$idx]}
        n=${d#dist_}
        [ -d "${resolved[$idx]}/$d" ] || {
            printf 'M11-GUARD: %s has no %s\n' "${resolved[$idx]}" "$d" >&2; bad=1; continue; }
        line=$(_m11_evidence_for "$evidence" "$d")
        if [ -z "$line" ]; then
            printf 'M11-GUARD: no evidence line for %s in %s\n' "$d" "$evidence" >&2; bad=1; continue
        fi
        case " $line " in
            *" rc=0 "*) : ;;
            *) printf 'M11-GUARD: %s evidence has no rc=0: %s\n' "$d" "$line" >&2; bad=1; continue ;;
        esac
        case "$line" in
            *run=*) : ;;
            *) printf 'M11-GUARD: %s evidence has no run=<jobid> at %s ranks: %s\n' \
                      "$d" "$n" "$line" >&2; bad=1; continue ;;
        esac
        local steps; steps=$(printf '%s\n' "$line" | sed -n 's/.*[[:space:]]steps=\([0-9]\+\).*/\1/p')
        if [ -z "$steps" ]; then
            printf 'M11-GUARD: %s evidence has no steps=<N>: %s\n' "$d" "$line" >&2; bad=1; continue
        fi
        if [ "$steps" -lt "$M11_MIN_PROMOTE_STEPS" ]; then
            printf 'M11-GUARD: %s ran only %s steps, below the %s-step floor: %s\n' \
                   "$d" "$steps" "$M11_MIN_PROMOTE_STEPS" "$line" >&2; bad=1; continue
        fi
        printf '  evidence ok  %-12s %-38s <- %s\n' "$d" "$line" "$(basename "${resolved[$idx]}")"
    done
    [ "$bad" = 0 ] || m11_die "promotion refused: $name is not fully evidenced (see above). \
A dist_N without a passing run of >= $M11_MIN_PROMOTE_STEPS steps AT N RANKS is exactly the \
NG5/MINCONN case: no offline metric caught it, and neither would a smoke run."

    # Build under a .partial name and rename only when everything is in place: an interrupted
    # promotion must never leave something that looks like a usable mesh directory.
    local tmp=$dst.partial.$$
    rm -rf "$tmp"
    mkdir -p "$tmp" || m11_die "cannot create $tmp"
    local f
    for f in "${M11_GATE_FILES[@]}" "${M11_EDGE_FILES[@]}"; do
        [ -f "$s/$f" ] && { cp -aL "$s/$f" "$tmp/$f" || m11_die "cp -aL failed for $f"; }
    done
    for idx in "${!dists[@]}"; do
        cp -aL "${resolved[$idx]}/${dists[$idx]}" "$tmp/" || m11_die "cp -aL failed for ${dists[$idx]}"
    done
    chmod -R u+w "$tmp" 2>/dev/null
    m11_assert_no_symlinks "$tmp"
    {
        printf '# M11 CERTIFIED mesh — promoted %s\n\n' "$(date '+%F %T')"
        printf 'mesh files : %s\n' "$s"
        for idx in "${!dists[@]}"; do
            printf 'partition  : %-12s <- %s\n' "${dists[$idx]}" "${resolved[$idx]}"
        done
        printf 'promoted-by: scripts/m11_guards.sh m11_promote\n'
        printf 'commit     : %s\n' "$(git -C "${ROOT:-/home/a/a270088/port_kokkos_part}" rev-parse --short HEAD 2>/dev/null || echo unknown)"
        printf 'dists      : %s\n\n' "${dists[*]}"
        printf '## evidence (one line per dist; smoke= is a model run at THAT rank count)\n'
        for d in "${dists[@]}"; do printf '%-12s %s\n' "$d" "$(_m11_evidence_for "$evidence" "$d")"; done
        printf '\n## source manifest at promotion time\n'
        sed 's/^/    /' "$s/MD5MANIFEST"
    } > "$tmp/MESH_PROVENANCE.md"
    _m11_md5_write_dir "$tmp" >/dev/null
    mv "$tmp" "$dst" || m11_die "could not rename $tmp to $dst"

    # The exception is logged where the campaign can find it, not only in the job output.
    mkdir -p "$M11_STATE_DIR"
    printf '%s  promote %-16s <- %s  dists=%s\n' \
        "$(date '+%F %T')" "$name" "$s" "${dists[*]}" >> "$M11_STATE_DIR/promotions.log"
    m11_ok "promoted $dst (${#dists[@]} dist(s)); provenance + manifest written"
}

# ---------------------------------------------------------------------------
# selftest — `bash scripts/m11_guards.sh selftest`
# Each negative case runs in a subshell because the guards exit 1 by design.
# ---------------------------------------------------------------------------

_m11_expect_abort() {                       # _m11_expect_abort <label> <cmd...>
    local label=$1; shift
    local out rc
    out=$( "$@" 2>&1 ); rc=$?
    if [ $rc -ne 0 ] && printf '%s' "$out" | grep -q 'M11-GUARD ABORT'; then
        printf '  PASS  %-46s (rc=%d) %s\n' "$label" "$rc" "$(printf '%s' "$out" | head -1)"
        return 0
    fi
    printf '  FAIL  %-46s (rc=%d) %s\n' "$label" "$rc" "$(printf '%s' "$out" | head -2 | tr '\n' ' ')"
    _M11_SELFTEST_FAIL=$((_M11_SELFTEST_FAIL + 1))
    return 1
}

_m11_expect_pass() {                        # _m11_expect_pass <label> <cmd...>
    local label=$1; shift
    local out rc
    out=$( "$@" 2>&1 ); rc=$?
    if [ $rc -eq 0 ]; then
        printf '  PASS  %-46s %s\n' "$label" "$(printf '%s' "$out" | tail -1)"
        return 0
    fi
    printf '  FAIL  %-46s (rc=%d) %s\n' "$label" "$rc" "$(printf '%s' "$out" | head -2 | tr '\n' ' ')"
    _M11_SELFTEST_FAIL=$((_M11_SELFTEST_FAIL + 1))
    return 1
}

m11_selftest() {
    _M11_SELFTEST_FAIL=0
    local scratch=${TMPDIR:-/tmp}/m11_guard_selftest.$$
    mkdir -p "$scratch"
    echo "M11 guard selftest — sandbox root $M11_SANDBOX_ROOT"

    echo "[1] m11_assert_sandbox rejects production paths"
    _m11_expect_abort "/pool farc"            m11_assert_sandbox /pool/data/AWICM/FESOM2/MESHES_FESOM2.1/farc
    _m11_expect_abort "/pool farc/dist_16"    m11_assert_sandbox /pool/data/AWICM/FESOM2/MESHES_FESOM2.1/farc/dist_16
    _m11_expect_abort "/pool resolved (pd1284)" m11_assert_sandbox /work/pd1284/AWICM/FESOM2/MESHES_FESOM2.1/farc
    _m11_expect_abort "private CORE2"         m11_assert_sandbox /work/ab0995/a270088/port2/mesh/core2
    _m11_expect_abort "private core2_wgt2"    m11_assert_sandbox /work/ab0995/a270088/port2/mesh/core2_wgt2
    _m11_expect_abort "\$HOME"                 m11_assert_sandbox "$HOME/port_kokkos_part"
    _m11_expect_abort "empty path"            m11_assert_sandbox ""
    _m11_expect_abort "sandbox-root itself"   m11_assert_sandbox "$M11_SANDBOX_ROOT"
    _m11_expect_abort ".. escape from sandbox" m11_assert_sandbox "$M11_SANDBOX_ROOT/../mesh/core2"

    echo "[2] m11_assert_sandbox rejects a SYMLINK that points out of the sandbox"
    mkdir -p "$M11_SANDBOX_ROOT" 2>/dev/null
    local link=$M11_SANDBOX_ROOT/.selftest_link
    ln -sfn /work/ab0995/a270088/port2/mesh/core2 "$link"
    _m11_expect_abort "symlink -> private CORE2"      m11_assert_sandbox "$link"
    _m11_expect_abort "symlink -> private CORE2/file" m11_assert_sandbox "$link/nlvls.out"
    rm -f "$link"

    echo "[3] m11_assert_sandbox accepts real sandbox paths"
    _m11_expect_pass "sandbox subdir"        m11_assert_sandbox "$M11_SANDBOX_ROOT/core2_m11"
    _m11_expect_pass "sandbox nested file"   m11_assert_sandbox "$M11_SANDBOX_ROOT/zoo/core2/a1/dist_8/rpart.out"

    echo "[4] namelist MeshPath guard"
    printf "&config\nMeshPath = '/pool/data/AWICM/FESOM2/MESHES_FESOM2.1/farc/'\n/\n" > "$scratch/nml_bad"
    printf "&config\nMeshPath = '%s/core2_m11/'\n/\n" "$M11_SANDBOX_ROOT"           > "$scratch/nml_good"
    printf "&config\nMeshPathX = 'nope'\n/\n"                                        > "$scratch/nml_none"
    _m11_expect_abort "MeshPath -> /pool"     m11_assert_namelist_meshpath "$scratch/nml_bad"
    _m11_expect_abort "MeshPath absent"       m11_assert_namelist_meshpath "$scratch/nml_none"
    _m11_expect_pass  "MeshPath -> sandbox"   m11_assert_namelist_meshpath "$scratch/nml_good"
    _m11_expect_abort "MeshPath != expected"  m11_assert_namelist_meshpath "$scratch/nml_good" "$M11_SANDBOX_ROOT/farc_m11"

    echo "[5] symlink sweep"
    mkdir -p "$scratch/dir_clean" "$scratch/dir_link"
    ln -sfn /pool "$scratch/dir_link/l"
    _m11_expect_pass  "clean dir"             m11_assert_no_symlinks "$scratch/dir_clean"
    _m11_expect_abort "dir with symlink"      m11_assert_no_symlinks "$scratch/dir_link"

    echo "[6] md5 manifest tamper detection"
    local mdir=$M11_SANDBOX_ROOT/.selftest_md5
    mkdir -p "$mdir"
    local f
    for f in "${M11_GATE_FILES[@]}"; do printf 'content of %s\n' "$f" > "$mdir/$f"; done
    _m11_expect_pass  "manifest write"        m11_md5_write "$mdir"
    _m11_expect_pass  "manifest verify"       m11_md5_check "$mdir"
    printf 'tampered\n' >> "$mdir/nlvls.out"
    _m11_expect_abort "manifest detects edit" m11_md5_check "$mdir"
    rm -f "$mdir/nlvls.out"
    _m11_expect_abort "manifest detects loss" m11_md5_check "$mdir"
    rm -rf "$mdir"

    echo "[7] m11_promote — evidence must be a protocol-length run at the dist's own rank count"
    local pdir=$M11_SANDBOX_ROOT/.selftest_promote
    rm -rf "$pdir"; mkdir -p "$pdir/dist_4" "$pdir/dist_8" "$pdir/dist_16"
    for f in "${M11_GATE_FILES[@]}" "${M11_EDGE_FILES[@]}"; do printf 'x %s\n' "$f" > "$pdir/$f"; done
    printf 'rpart\n' > "$pdir/dist_4/rpart.out"; printf 'rpart\n' > "$pdir/dist_8/rpart.out"
    printf 'rpart\n' > "$pdir/dist_16/rpart.out"
    m11_md5_write "$pdir" >/dev/null
    local ev=$scratch/evidence.txt
    printf 'dist_4  run=111 steps=3000 rc=0 race=222 delta=-7.5%%\ndist_8  race=333 delta=-1.0%%\n' > "$ev"
    # A second arm dir of the SAME mesh, and a third that is a different mesh entirely.
    local pdir2=$M11_SANDBOX_ROOT/.selftest_promote2
    rm -rf "$pdir2"; mkdir -p "$pdir2/dist_32"
    for f in "${M11_GATE_FILES[@]}" "${M11_EDGE_FILES[@]}"; do cp "$pdir/$f" "$pdir2/$f"; done
    printf 'rpart\n' > "$pdir2/dist_32/rpart.out"
    m11_md5_write "$pdir2" >/dev/null
    local pdir3=$M11_SANDBOX_ROOT/.selftest_promote3
    rm -rf "$pdir3"; mkdir -p "$pdir3/dist_64"
    for f in "${M11_GATE_FILES[@]}" "${M11_EDGE_FILES[@]}"; do printf 'DIFFERENT %s\n' "$f" > "$pdir3/$f"; done
    printf 'rpart\n' > "$pdir3/dist_64/rpart.out"
    m11_md5_write "$pdir3" >/dev/null
    local saveroot=$M11_PROMOTE_ROOT
    M11_PROMOTE_ROOT=$scratch/../m11_guard_selftest.$$/promote_root
    _m11_expect_abort "promote root outside the sanctioned tree" \
        m11_promote --src "$pdir" --name t1 --evidence "$ev" dist_4
    M11_PROMOTE_ROOT=$saveroot
    _m11_expect_abort "dist_8 has no run= record" \
        m11_promote --src "$pdir" --name .selftest_t2 --evidence "$ev" dist_4 dist_8
    printf 'dist_8  run=444 steps=3000 rc=1 race=333\n' >> "$ev"
    _m11_expect_abort "dist_8 run record is rc=1" \
        m11_promote --src "$pdir" --name .selftest_t3 --evidence "$ev" dist_4 dist_8
    # The NG5 case: a short run that passes. This is the one a smoke-only rule would have let
    # through, so it must be refused on step count alone.
    printf 'dist_16 run=555 steps=5 rc=0 race=666 delta=-9.96%%\n' >> "$ev"
    _m11_expect_abort "dist_16 passed, but only 5 steps (the NG5 case)" \
        m11_promote --src "$pdir" --name .selftest_t5 --evidence "$ev" dist_4 dist_16
    _m11_expect_abort "promote source outside the sandbox" \
        m11_promote --src /pool/data/AWICM/FESOM2/MESHES_FESOM2.1/farc --name .selftest_t4 \
                    --evidence "$ev" dist_4
    printf 'dist_32 run=777 steps=3000 rc=0 race=888 delta=-3.8%%\n' >> "$ev"
    printf 'dist_64 run=999 steps=3000 rc=0\n' >> "$ev"
    _m11_expect_abort "two --src that are different MESHES" \
        m11_promote --name .selftest_t6 --evidence "$ev" \
                    --src "$pdir" dist_4 --src "$pdir3" dist_64
    _m11_expect_abort "dist_ named before any --src" \
        m11_promote --name .selftest_t7 --evidence "$ev" dist_4 --src "$pdir"
    _m11_expect_pass  "promote dist_4 (evidenced)" \
        m11_promote --src "$pdir" --name .selftest_ok --evidence "$ev" dist_4
    # The campaign's actual shape: rank-dependent winners from DIFFERENT arms of one mesh.
    _m11_expect_pass  "promote dist_4 + dist_32 from two arms" \
        m11_promote --name .selftest_multi --evidence "$ev" \
                    --src "$pdir" dist_4 --src "$pdir2" dist_32
    _m11_expect_abort "promote refuses to overwrite" \
        m11_promote --src "$pdir" --name .selftest_ok --evidence "$ev" dist_4
    rm -rf "$pdir" "$pdir2" "$pdir3" "$M11_PROMOTE_ROOT/.selftest_ok" "$M11_PROMOTE_ROOT/.selftest_multi"

    rm -rf "$scratch"
    echo
    if [ "$_M11_SELFTEST_FAIL" -eq 0 ]; then
        echo "M11 guard selftest: ALL PASS"
        return 0
    fi
    echo "M11 guard selftest: $_M11_SELFTEST_FAIL FAILURE(S)"
    return 1
}

# Executed rather than sourced?
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    case "${1:-}" in
        selftest) shift; m11_selftest "$@" ;;
        "")  echo "usage: bash $0 selftest   |   source $0   (library)"; exit 2 ;;
        *)   "$@" ;;   # allow `bash m11_guards.sh m11_check_sources` from jobs
    esac
fi
